#!/bin/sh
GREENBOLD='\033[0;32;1m' # 1m means bold
REDBOLD='\033[0;31;1m'
echo "${GREENBOLD} precommit works"
git secret hide -m
echo "${REDBOLD} this hook will always block commit, exiting with -1"
exit -1
